apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: blue
  name: blue
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: blue
status:
  loadBalancer: {}
