apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: linkerd
  name: linkerd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: linkerd
    spec:
      containers:
      - args:
        - /config.yaml
        env:
        - name: SERVICE_IGNORE
          value: "true"
        image: buoyantio/linkerd:1.3.6
        name: linkerd
        ports:
        - containerPort: 9990
        - containerPort: 4140
        - containerPort: 4141
        resources: {}
        volumeMounts:
        - mountPath: /config.yaml
          name: linkerd-claim0
      restartPolicy: Always
      volumes:
      - name: linkerd-claim0
        persistentVolumeClaim:
          claimName: linkerd-claim0
status: {}
