admin:
  ip: 0.0.0.0
  port: 9991

# NOTE: We need to create the dtabs manually to route services
storage:
  kind: io.l5d.consul
  host: consul
  port: 8500
  datacenter: dc1
  pathPrefix: /namerd/dtabs
  readConsistencyMode: stale
  writeConsistencyMode: stale
  backoff:
    kind: jittered
    minMs: 10
    maxMs: 10000

## Uncomment to enable in-memory storage. NOTE: Don't use this in production!
# storage:
#   kind: io.l5d.inMemory
#   namespaces:
#     consul_ingress: |
#       /svc => /#/io.l5d.consul_ingress/dc1;
#     consul_egress: |
#       /svc => /#/io.l5d.consul_egress/dc1;

namers:
- kind: io.l5d.consul
  prefix: /io.l5d.consul_ingress
  host: consul
  port: 8500
  includeTag: false
  useHealthCheck: false
  healthStatuses:
    - "passing"
    - "warning"
  setHost: false # Must be false, else it won't work
  consistencyMode: stale
  failFast: true
  preferServiceAddress: true

- kind: io.l5d.consul
  prefix: /io.l5d.consul_egress
  host: consul
  port: 8500
  includeTag: false
  useHealthCheck: false
  healthStatuses:
    - "passing"
    - "warning"
  setHost: true
  consistencyMode: stale
  failFast: true
  preferServiceAddress: true

interfaces:
  # used by linkerds to receive updates
  - kind: io.l5d.thriftNameInterpreter
    ip: 0.0.0.0
    port: 4100

  # used by `namerctl` to manage configuration
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180