defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]

[docker]
domain = "docker.local"
watch = true

[consulCatalog]
endpoint = "consul:8500"
exposedByDefault = false # You have to manually add the tags to enable the service to be discovered
domain = "consul.localhost"
prefix = "traefik" # All tags have to be prefixed with traefik, e.g. traefik.enable=true

[tracing]
	Backend = "jaeger"
	ServiceName = "traefik"
	[tracing.jaeger]
		SamplingServerURL = "http://tracing:5778/sampling"
		SamplingType = "const"
		SamplingParam = 1.0
		LocalAgentHostPort = "tracing:5775" # The example in traefik documentation doesn't work: LocalAgentHostPort = "tracing:6832"
	
[metrics]
	[metrics.prometheus]
		entryPoint = "http"
		buckets = [0.1, 0.3, 1.2, 5.0]